services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    #services
    azuracom_process.handler_provider:
        class: Azuracom\ProcessBundle\Handler\HandlerProvider
    
    azuracom_process.helper:
        class: Azuracom\ProcessBundle\Helper\ProcessHelper
        
    azuracom_process.monolog.process_handler:
        class: Azuracom\ProcessBundle\Monolog\Handler\ProcessHandler

    Azuracom\ProcessBundle\EventListener\ProcessSubscriber:
        public: false
        tags:
            - { name: 'doctrine.event_subscriber' }      
                        

    #aliases
    Azuracom\ProcessBundle\Handler\HandlerProviderInterface: '@azuracom_process.handler_provider'   
    Azuracom\ProcessBundle\Helper\ProcessHelperInterface: '@azuracom_process.helper'       
        
parameters:
    azuracom_process.types: []
    azuracom_process.status: []