Azuracom\ProcessBundle\Model\ProcessResourceTag:
    type: mappedSuperclass
    table: process_resource_tag
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        className:
            type: string
            length: 255

        resourceId:
            type: string
            length: 255

        resourceCode:
            type: string
            length: 255
            nullable: true

        comment:
            type: string
            length: 255
            nullable: true

    manyToOne:
        process:
            targetEntity: Azuracom\ProcessBundle\Model\ProcessInterface
            inversedBy: resourceTags
            joinColumn:
                name: process_id
                referencedColumnName: id


