Azuracom\ProcessBundle\Model\Process:
    type: mappedSuperclass
    table: process
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255

        status:
            type: string
            length: 255 
            nullable: true             

        uniqueId:
            type: string
            length: 255 
            nullable: true

        originalFilename:
            type: string
            length: 255  
            nullable: true      
            
        filename:
            type: string
            length: 255 
            nullable: true 

        options:
            type: array
            nullable: true 
            
        startedAt:
            type: datetime
            nullable: true        

        endedAt:
            type: datetime   
            nullable: true     
            
        resolved:
            type: boolean   

        createdAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update

    oneToMany:
        resourceTags:
            targetEntity: Azuracom\ProcessBundle\Model\ProcessResourceTagInterface
            mappedBy: process  
            cascade: ['persist']
            orphanRemoval: true     

    manyToOne:
        user:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id                         