services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    #public services
    azuracom_process.handler_provider:
        class: Azuracom\ProcessBundle\Handler\HandlerProvider
    
    azuracom_process.helper:
        class: Azuracom\ProcessBundle\Helper\ProcessHelper
        arguments:
            $typeList: '%azuracom_process.types%'
            $statusList: '%azuracom_process.status%'
        
    azuracom_process.monolog.process_handler:
        class: Azuracom\ProcessBundle\Monolog\Handler\ProcessHandler




    #private services
    #Listeners
    Azuracom\ProcessBundle\EventListener\ProcessSubscriber:
        public: false
        tags:
            - { name: 'doctrine.event_subscriber' }  

    Azuracom\ProcessBundle\EventListener\ORMUserMappingSubscriber:
        arguments: ['@sylius.resource_registry',null]
        public: false
        tags:
            - { name: 'doctrine.event_subscriber' , priority: 8193 }              
            
            
    azuracom_process.custom_factory.process_resource_tag:
        class: Azuracom\ProcessBundle\Factory\ProcessResourceTagFactory
        decorates: 'azuracom_process.factory.process_resource_tag'
        decoration_priority: 256
        public: false
        arguments: ['@azuracom_process.custom_factory.process_resource_tag.inner']     
        
    azuracom_process.custom_factory.process:
        class: Azuracom\ProcessBundle\Factory\ProcessFactory
        decorates: 'azuracom_process.factory.process'
        decoration_priority: 256
        public: false
        arguments: ['@azuracom_process.custom_factory.process.inner','@security.token_storage']            

    #commands
    Azuracom\ProcessBundle\Command\ClearProcessCommand:
        public: false
        tags:
            - { name: 'console.command' }    
            
    Azuracom\ProcessBundle\Command\DeferProcessHandleCommand:
        public: false
        tags:
            - { name: 'console.command' } 
            
    Azuracom\ProcessBundle\Form\:
        resource: '../src/Form'
        tags: ['form.type']
                        

    #messenger
    Azuracom\ProcessBundle\Messenger\ProcessMessageHandler:
        tags: [messenger.message_handler]

    #aliases
    Azuracom\ProcessBundle\Handler\HandlerProviderInterface: '@azuracom_process.handler_provider'   
    Azuracom\ProcessBundle\Helper\ProcessHelperInterface: '@azuracom_process.helper'       
        
parameters:
    azuracom_process.types: []
    azuracom_process.status: []