services:
    azuracom_process.admin.process:
        class: '%azuracom_process.admin.process.class%'
        arguments: [null, '%azuracom_process.model.process.class%', ~]
        calls:
            - [setProcessHelper, ['@azuracom_process.helper']]
            - [setHandlerProvider, ['@azuracom_process.handler_provider']]
            - [setTokenStorage, ['@security.token_storage']]
            - [setMessengerBus, ['@?messenger.default_bus']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Process }

    azuracom_process.admin.process_resource_tag:
        class: '%azuracom_process.admin.process_resource_tag.class%'
        arguments: [null, '%azuracom_process.model.process_resource_tag.class%', ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
            
    Azuracom\ProcessBundle\Controller\ProcessAdminController:
        tags: ['controller.service_arguments']            
